### ISSUE TITLE
Audit Template: Add integration test for BuildingSync import

### ISSUE THREAD

**Issue by macintoshpie** [SEED-platform/seed#2972]
## context
SEED supports the import of BuildingSync files which were exported from [Audit Template](https://buildingenergyscore.energy.gov/rp/buildings) (AT).

## task
TLDR; create an automated test which fetches a BuildingSync file from Audit Template, runs it through SEED's BuildingSync import, verifies everything about the building looks good.

More specifically:
- [ ] Create an account on Audit Template for SEED to use. This will be like the account we use for Portfolio Manager
- [ ] Add building(s) to SEED's Audit Template account. Maybe some of AT's [current example BuildingSync files](https://buildingenergyscore.energy.gov/resources)?
- [ ] Create a simple client for the Audit Template API to fetch BuildingSync files from the account we created
- [ ] Add tests which use Audit Template client to fetch our buildings then import them

Other Notes:
- this should work kind of like SEED's [Portfolio Manager tests](https://github.com/SEED-platform/seed/blob/develop/seed/tests/test_portfoliomanager.py). We should add a [similar decorator](https://github.com/SEED-platform/seed/blob/701e208c69906734bdcfcf09093ad105ffbeec2e/seed/tests/test_portfoliomanager.py#L25) which will skip some tests if it's not configured properly or if the server is down.

## Why?
- ensures our BSync import stays compatible with Audit Template (currently we will have to manually export a BSync file from AT, add it to the tests directory)
- initial step towards API integration with AT, allowing SEED users to pull properties from AT

## resources
- [AT API Overview](https://buildingenergyscore.energy.gov/pages/api)
- [AT API Docs](https://buildingenergyscore.energy.gov/apidoc)
