### ISSUE TITLE
SCEP features

### ISSUE THREAD

**Issue by haneslinger** [SEED-platform/seed#4110]
**Insight Property page**
- [ ] when you refresh the page, your dropdown selection and hidden legend items are maintained. https://github.com/SEED-platform/seed/pull/3994
- [ ] ‘Create a label’ from the legend [#3859](https://github.com/SEED-platform/seed/issues/3859)
- [ ] Add rank sort to drop down [ #4030](https://github.com/SEED-platform/seed/pull/4030) (
- [ ] Add more information to the tabular data [#4075](https://github.com/SEED-platform/seed/pull/4075) 
- [ ] Zoom in and zoom out of the visual. [#3879](https://github.com/SEED-platform/seed/pull/3879)

**Program overview page**
- [ ] remove table on this page https://github.com/SEED-platform/seed/pull/4007
- [ ] Toolip: Add numbers and percentages of the bar on the visualization that you are hovering over [#4070](https://github.com/SEED-platform/seed/pull/4077)
- [ ]  Direct to property insight on click of program overview column #4011

**Summary/ Default Reports page**
- [ ] Move the Reports page to the Program Overview/Insights world as it’s own tab.  #4031
- [ ] Correctly handle the categorical variables on scatter plots [#4085](https://github.com/SEED-platform/seed/pull/4085) (NOT ON DEV1 YET)

**Comment by RDmitchell** [comment]
@haneslinger / @isalanglois -- I understand you are making these changes because of SCEP requests, but I'm not sure removing the list of compliant and non-compliant buildings on the Program Overview page is such a good idea ... ???

It doesn't take up much real estate space -- 3 lines at the bottom of the page. 

Can't they just ignore it / not click on it?

**Comment by RDmitchell** [comment]
@haneslinger -- is this deployed to the dev1 server for testing?

**Comment by haneslinger** [comment]
> @haneslinger -- is this deployed to the dev1 server for testing?

I believe so, yes

**Comment by RDmitchell** [comment]
instance: dev1
SHA: 6bec6092b
Org: BPS Test

**Insight Property page**
- [ ] when you refresh the page, your dropdown selection and hidden legend items are maintained. https://github.com/SEED-platform/seed/pull/3994
  RM - This is complete
- [ ] ‘Create a label’ from the legend [#3859](https://github.com/SEED-platform/seed/issues/3859)
  RM - I guess this would be used when you strike out everything but "Compliant" and then add the Compliant label to those records -- it wasn't intuitively obvious that this would be how it works, but it does work that way 
- [ ] Add rank sort to drop down [ #4030](https://github.com/SEED-platform/seed/pull/4030)
  _**RM -- I don't understand what this is about -- please give more detail about the feature so I can test it**_
- [ ] Add more information to the tabular data [#4075](https://github.com/SEED-platform/seed/pull/4075)
  RM  -- The table now contains the X axis with label (ie, X: Year Built) and the Y-axis with label (ie, Y: Site EUI)
  ![image](https://github.com/SEED-platform/seed/assets/6314950/688944e4-47f5-40ce-9e4d-9e557b6c1959)
- [ ] Zoom in and zoom out of the visual. [#3879](https://github.com/SEED-platform/seed/pull/3879)
  RM -- zooming seems to work

**Program overview page**
- [ ] remove table on this page https://github.com/SEED-platform/seed/pull/4007
  RM -- table is no longer there (now on Property Insights)
- [ ] Toolip: Add numbers and percentages of the bar on the visualization that you are hovering over [#4070](https://github.com/SEED-platform/seed/pull/4077)
  RM -- Done
  ![image](https://github.com/SEED-platform/seed/assets/6314950/eaaa3738-47fa-45b4-85f6-57b43b88e639)
- [ ]  Direct to property insight on click of program overview column #4011
  RM -- When you click on either the Compliant or Non-Compliant section of the bar graph, the program goes to the Property Insights page and displays the appropriate set of data, ie, either just the Compliant dots or just the Non-Compliant triangles, with the correct cycle being selected

**Summary/ Default Reports page**
- [ ] Move the Reports page to the Program Overview/Insights world as it’s own tab.  #4031
  RM -- Reports are now under Insights 
  ![image](https://github.com/SEED-platform/seed/assets/6314950/bb15321e-aafb-4e5b-94c3-592b396166be)
- [ ] Correctly handle the categorical variables on scatter plots [#4085](https://github.com/SEED-platform/seed/pull/4085) (NOT ON DEV1 YET)

**Comment by RDmitchell** [comment]
So the only 2 left for me to test are

- [ ] Add rank sort to drop down [ #4030](https://github.com/SEED-platform/seed/pull/4030)
  _**RM -- I don't understand what this is about -- please give more detail about the feature so I can test it**_

- [ ] Correctly handle the categorical variables on scatter plots [#4085](https://github.com/SEED-platform/seed/pull/4085) (NOT ON DEV1 YET)

**Comment by RDmitchell** [comment]
instance: dev1
SHA: 6bec6092b
Org: BPS Test

- [ ] Correctly handle the categorical variables on scatter plots [#4085](https://github.com/SEED-platform/seed/pull/4085) (NOT ON DEV1 YET)

Actually I think the Default Report scatter plots are working properly -- 
@haneslinger -- is this now on dev1?

![image](https://github.com/SEED-platform/seed/assets/6314950/1630fbe7-2e6a-4daf-8891-7cc860ccad10)

**Comment by RDmitchell** [comment]
@haneslinger -- so I just need more detail for this one so that I know what to test

- [ ] Add rank sort to drop down [ #4030](https://github.com/SEED-platform/seed/pull/4030)
  _**RM -- I don't understand what this is about -- please give more detail about the feature so I can test it**_

**Comment by RDmitchell** [comment]
Instance: dev1
SHA: 6bec6092b
Org: BPT Test

@haneslinger -- so in the case below, the non-compliant properties are being ranked by the X-Axis, which is Year Built? 

So it is going from the highest year, 1962, to the lowest numbericavalue of year, ie, 1880?

![image](https://github.com/SEED-platform/seed/assets/6314950/3d0d2b4c-25d5-4d7e-b5a7-19a3403a76f8)

**Comment by RDmitchell** [comment]
I don't see Rank Sort on the Property Insights page any more, but everything else seems to be there from this issue, so I am going to close it.
